<html>
    <head>
        <title>Tampil Data Matakuliah</title>
    </head>
    <body>
        <center>
            <table>
                <tr>
                    <th colspan="3">
                        Tampil Data Matakuliah
                    </th>
                </tr>
                <tr>
                    <th colspan="3">
                        <hr>
                    </th>
                </tr>
                <tr>
                    <th>
                        Nama
                    </th>
                    <th>:</th>
                    <td>
                        <?=$nama;?>
                    </td>
                </tr>
                <tr>
                    <th>
                        NIM
                    </th>
                    <th>:</th>
                    <td>
                        <?=$nim;?>
                    </td>
                </tr>
                <tr>
                    <th>
                        Kelas
                    </th>
                    <th>:</th>
                    <td>
                        <?=$kelas;?>
                    </td>
                </tr>
                <tr>
                    <th>
                        tanggal lahir
                    </th>
                    <th>:</th>
                    <td>
                        <?=$tgl;?>
                    </td>
                </tr>
                <tr>
                    <th>
                        Tempat lahir
                    </th>
                    <th>:</th>
                    <td>
                        <?=$tmpt;?>
                    </td>
                </tr>
                <tr>
                    <th>
                        Alamat
                    </th>
                    <th>:</th>
                    <td>
                        <?=$alamat;?>
                    </td>
                </tr>
                <tr>
                    <th>
                        Agama
                    </th>
                    <th>:</th>
                    <td>
                        <?=$agama;?>
                    </td>
                </tr>
                <tr>
                    <td colspan="3" align="center">
                        <a href="<?= base_url('login');?>">Keluar</a>
                    </td>
                </tr>
            </table>
        </center>
    </body>
</html>